#!/usr/bin/env tsx
/**
 * bundle-assets.ts
 *
 * Reads PrepOps engine files from the repo root and generates
 * src/assets/engine.ts — a single TypeScript module that bundles
 * all prompts, personas, incidents, rubrics, and knowledge topics.
 *
 * Run:  npm run bundle
 * Auto: runs before `wrangler dev` and `wrangler deploy` via package.json scripts.
 */

import { readFileSync, writeFileSync, readdirSync, existsSync } from 'fs';
import { resolve, join, basename } from 'path';

const ROOT = resolve(__dirname, '../../');
const OUT  = resolve(__dirname, '../src/assets/engine.ts');

function read(rel: string): string {
  const abs = join(ROOT, rel);
  if (!existsSync(abs)) { console.warn(`WARN: missing ${rel}`); return ''; }
  return readFileSync(abs, 'utf8');
}

function readDir(rel: string, ext = '.yaml'): Record<string, string> {
  const abs = join(ROOT, rel);
  if (!existsSync(abs)) return {};
  return Object.fromEntries(
    readdirSync(abs)
      .filter(f => f.endsWith(ext))
      .map(f => [basename(f, ext), readFileSync(join(abs, f), 'utf8')]),
  );
}

function escape(s: string): string {
  return s.replace(/\\/g, '\\\\').replace(/`/g, '\\`').replace(/\$\{/g, '\\${');
}

function ts(key: string, val: string): string {
  return `export const ${key} = \`${escape(val)}\`;\n`;
}

function tsRecord(varName: string, obj: Record<string, string>): string {
  const entries = Object.entries(obj)
    .map(([k, v]) => `  '${k}': \`${escape(v)}\``)
    .join(',\n');
  return `export const ${varName}: Record<string, string> = {\n${entries}\n};\n`;
}

// ── Prompts ──────────────────────────────────────────────────────────────────
const prompts: Record<string, string> = {};
for (const file of readdirSync(join(ROOT, 'prompts')).filter(f => f.endsWith('.md'))) {
  prompts[basename(file, '.md')] = read(`prompts/${file}`);
}

// ── Personas ─────────────────────────────────────────────────────────────────
const personas = readDir('personas');

// ── Incidents ────────────────────────────────────────────────────────────────
const incidents: Record<string, string> = {};
for (const domain of ['kubernetes', 'linux', 'networking', 'sre']) {
  for (const f of readdirSync(join(ROOT, `incidents/${domain}`)).filter(f => f.endsWith('.yaml'))) {
    incidents[`${domain}/${basename(f, '.yaml')}`] = read(`incidents/${domain}/${f}`);
  }
}

// ── Incident templates ────────────────────────────────────────────────────────
const incidentTemplates = readDir('incident-templates');

// ── Rubrics + evaluation template ─────────────────────────────────────────────
const rubrics: Record<string, string> = {
  dimensions:     read('rubrics/dimensions.yaml'),
  hiring_signals: read('rubrics/hiring-signals.yaml'),
  evaluation:     read('templates/evaluation_rubric.yaml'),
};

// ── Knowledge topics ─────────────────────────────────────────────────────────
const knowledge: Record<string, string> = {};
for (const domain of ['kubernetes', 'linux', 'aws', 'networking', 'terraform', 'sre']) {
  const dir = join(ROOT, `knowledge/${domain}`);
  if (!existsSync(dir)) continue;
  for (const f of readdirSync(dir).filter(f => f.endsWith('.yaml'))) {
    knowledge[`${domain}/${basename(f, '.yaml')}`] = read(`knowledge/${domain}/${f}`);
  }
}

// ── CORE prompt ──────────────────────────────────────────────────────────────
const CORE = `You are PrepOps, an AI interview coach for Infrastructure, DevOps, SRE, Cloud, and Platform Engineering.

Philosophy:
- Train reasoning and production thinking — never memorization
- Ask follow-up questions like a real technical interviewer
- Surface misconceptions actively — name them when you see them
- Give specific feedback; never say "good effort" without naming exactly what was good
- Frame feedback as hiring signal: Strong Hire / Lean Hire / Borderline / Lean No Hire / No Hire

Be direct, specific, production-grounded. Keep responses conversational.`;

// ── Topics list (full-curriculum topics) ─────────────────────────────────────
const TOPICS = [
  { id: 'kubernetes', display: 'Kubernetes', coverage: 'full' as const },
  { id: 'linux',      display: 'Linux',      coverage: 'full' as const },
  { id: 'aws',        display: 'AWS',        coverage: 'full' as const },
  { id: 'networking', display: 'Networking', coverage: 'full' as const },
  { id: 'terraform',  display: 'Terraform',  coverage: 'full' as const },
  { id: 'sre',        display: 'SRE',        coverage: 'full' as const },
];

// ── Generate engine.ts ────────────────────────────────────────────────────────
const output = [
  '// AUTO-GENERATED by scripts/bundle-assets.ts — do not edit manually.',
  '// Run: npm run bundle to regenerate after changing prompts/personas/incidents.',
  '',
  ts('CORE', CORE),
  tsRecord('PROMPTS', prompts),
  tsRecord('PERSONAS', personas),
  tsRecord('INCIDENTS', incidents),
  tsRecord('INCIDENT_TEMPLATES', incidentTemplates),
  tsRecord('RUBRICS', rubrics),
  tsRecord('KNOWLEDGE', knowledge),
  `export const TOPICS: Array<{ id: string; display: string; coverage: 'full' | 'general' }> = ${JSON.stringify(TOPICS, null, 2)};\n`,
].join('\n');

writeFileSync(OUT, output, 'utf8');
console.log(`✓ engine.ts written (${Math.round(output.length / 1024)}KB) — ${Object.keys(prompts).length} prompts, ${Object.keys(personas).length} personas, ${Object.keys(incidents).length} incidents`);
